### ISSUE TITLE
Ticket system?

### ISSUE THREAD

**Issue by gomsoop** [cambierr/SmartCarts#4]
Hello! I am really a big fan of "minecart rail system" techy guy. Your plugin looks awesome and would it be possible to have a ticket system in it. Maybe a book with some info {"station#"} or so, and when the passenger passes a sign and if this ticket matches the station code, the track switches inside to the station.
When the player stops at the station block, the passenger is auto exited from the cart and the ticket disappears.

**Comment by cambierr** [comment]
Hi!

Actually, it's already partially implemented: Intersections gives you the possibility to route a cart according to any conditions on cart content or cart name.

What this means, is that you just have to rename a cart with a destination name and program your intersections so that they will route this name to a final destination, and you're done!

Is this what you are looking for? or you really need a "ticket" system? :)

**Comment by cambierr** [comment]
related to #6 so i'm locking this one
